// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: imageclass.proto

package youtu;

public final class Imageclass {
  private Imageclass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClassRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes photoid = 1;
    /**
     * <code>required bytes photoid = 1;</code>
     */
    boolean hasPhotoid();
    /**
     * <code>required bytes photoid = 1;</code>
     */
    com.google.protobuf.ByteString getPhotoid();

    // required bytes data = 2;
    /**
     * <code>required bytes data = 2;</code>
     */
    boolean hasData();
    /**
     * <code>required bytes data = 2;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code youtu.ClassRequest}
   */
  public static final class ClassRequest extends
      com.google.protobuf.GeneratedMessage
      implements ClassRequestOrBuilder {
    // Use ClassRequest.newBuilder() to construct.
    private ClassRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClassRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClassRequest defaultInstance;
    public static ClassRequest getDefaultInstance() {
      return defaultInstance;
    }

    public ClassRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClassRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              photoid_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return youtu.Imageclass.internal_static_youtu_ClassRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return youtu.Imageclass.internal_static_youtu_ClassRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              youtu.Imageclass.ClassRequest.class, youtu.Imageclass.ClassRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<ClassRequest> PARSER =
        new com.google.protobuf.AbstractParser<ClassRequest>() {
      public ClassRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClassRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClassRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bytes photoid = 1;
    public static final int PHOTOID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString photoid_;
    /**
     * <code>required bytes photoid = 1;</code>
     */
    public boolean hasPhotoid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes photoid = 1;</code>
     */
    public com.google.protobuf.ByteString getPhotoid() {
      return photoid_;
    }

    // required bytes data = 2;
    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>required bytes data = 2;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private void initFields() {
      photoid_ = com.google.protobuf.ByteString.EMPTY;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPhotoid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, photoid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, photoid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static youtu.Imageclass.ClassRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static youtu.Imageclass.ClassRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static youtu.Imageclass.ClassRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static youtu.Imageclass.ClassRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static youtu.Imageclass.ClassRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static youtu.Imageclass.ClassRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static youtu.Imageclass.ClassRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static youtu.Imageclass.ClassRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static youtu.Imageclass.ClassRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static youtu.Imageclass.ClassRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(youtu.Imageclass.ClassRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code youtu.ClassRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements youtu.Imageclass.ClassRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return youtu.Imageclass.internal_static_youtu_ClassRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return youtu.Imageclass.internal_static_youtu_ClassRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                youtu.Imageclass.ClassRequest.class, youtu.Imageclass.ClassRequest.Builder.class);
      }

      // Construct using youtu.Imageclass.ClassRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        photoid_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return youtu.Imageclass.internal_static_youtu_ClassRequest_descriptor;
      }

      public youtu.Imageclass.ClassRequest getDefaultInstanceForType() {
        return youtu.Imageclass.ClassRequest.getDefaultInstance();
      }

      public youtu.Imageclass.ClassRequest build() {
        youtu.Imageclass.ClassRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public youtu.Imageclass.ClassRequest buildPartial() {
        youtu.Imageclass.ClassRequest result = new youtu.Imageclass.ClassRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.photoid_ = photoid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof youtu.Imageclass.ClassRequest) {
          return mergeFrom((youtu.Imageclass.ClassRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(youtu.Imageclass.ClassRequest other) {
        if (other == youtu.Imageclass.ClassRequest.getDefaultInstance()) return this;
        if (other.hasPhotoid()) {
          setPhotoid(other.getPhotoid());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPhotoid()) {
          
          return false;
        }
        if (!hasData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        youtu.Imageclass.ClassRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (youtu.Imageclass.ClassRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes photoid = 1;
      private com.google.protobuf.ByteString photoid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes photoid = 1;</code>
       */
      public boolean hasPhotoid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes photoid = 1;</code>
       */
      public com.google.protobuf.ByteString getPhotoid() {
        return photoid_;
      }
      /**
       * <code>required bytes photoid = 1;</code>
       */
      public Builder setPhotoid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        photoid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes photoid = 1;</code>
       */
      public Builder clearPhotoid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        photoid_ = getDefaultInstance().getPhotoid();
        onChanged();
        return this;
      }

      // required bytes data = 2;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes data = 2;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>required bytes data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes data = 2;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:youtu.ClassRequest)
    }

    static {
      defaultInstance = new ClassRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:youtu.ClassRequest)
  }

  public interface ClassResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated string tags = 1;
    /**
     * <code>repeated string tags = 1;</code>
     */
    java.util.List<java.lang.String>
    getTagsList();
    /**
     * <code>repeated string tags = 1;</code>
     */
    int getTagsCount();
    /**
     * <code>repeated string tags = 1;</code>
     */
    java.lang.String getTags(int index);
    /**
     * <code>repeated string tags = 1;</code>
     */
    com.google.protobuf.ByteString
        getTagsBytes(int index);

    // repeated float sim = 2;
    /**
     * <code>repeated float sim = 2;</code>
     */
    java.util.List<java.lang.Float> getSimList();
    /**
     * <code>repeated float sim = 2;</code>
     */
    int getSimCount();
    /**
     * <code>repeated float sim = 2;</code>
     */
    float getSim(int index);
  }
  /**
   * Protobuf type {@code youtu.ClassResponse}
   */
  public static final class ClassResponse extends
      com.google.protobuf.GeneratedMessage
      implements ClassResponseOrBuilder {
    // Use ClassResponse.newBuilder() to construct.
    private ClassResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClassResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClassResponse defaultInstance;
    public static ClassResponse getDefaultInstance() {
      return defaultInstance;
    }

    public ClassResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClassResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                tags_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              tags_.add(input.readBytes());
              break;
            }
            case 21: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                sim_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000002;
              }
              sim_.add(input.readFloat());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                sim_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                sim_.add(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          tags_ = new com.google.protobuf.UnmodifiableLazyStringList(tags_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          sim_ = java.util.Collections.unmodifiableList(sim_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return youtu.Imageclass.internal_static_youtu_ClassResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return youtu.Imageclass.internal_static_youtu_ClassResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              youtu.Imageclass.ClassResponse.class, youtu.Imageclass.ClassResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<ClassResponse> PARSER =
        new com.google.protobuf.AbstractParser<ClassResponse>() {
      public ClassResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClassResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClassResponse> getParserForType() {
      return PARSER;
    }

    // repeated string tags = 1;
    public static final int TAGS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList tags_;
    /**
     * <code>repeated string tags = 1;</code>
     */
    public java.util.List<java.lang.String>
        getTagsList() {
      return tags_;
    }
    /**
     * <code>repeated string tags = 1;</code>
     */
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <code>repeated string tags = 1;</code>
     */
    public java.lang.String getTags(int index) {
      return tags_.get(index);
    }
    /**
     * <code>repeated string tags = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTagsBytes(int index) {
      return tags_.getByteString(index);
    }

    // repeated float sim = 2;
    public static final int SIM_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Float> sim_;
    /**
     * <code>repeated float sim = 2;</code>
     */
    public java.util.List<java.lang.Float>
        getSimList() {
      return sim_;
    }
    /**
     * <code>repeated float sim = 2;</code>
     */
    public int getSimCount() {
      return sim_.size();
    }
    /**
     * <code>repeated float sim = 2;</code>
     */
    public float getSim(int index) {
      return sim_.get(index);
    }

    private void initFields() {
      tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      sim_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < tags_.size(); i++) {
        output.writeBytes(1, tags_.getByteString(i));
      }
      for (int i = 0; i < sim_.size(); i++) {
        output.writeFloat(2, sim_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < tags_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(tags_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getTagsList().size();
      }
      {
        int dataSize = 0;
        dataSize = 4 * getSimList().size();
        size += dataSize;
        size += 1 * getSimList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static youtu.Imageclass.ClassResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static youtu.Imageclass.ClassResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static youtu.Imageclass.ClassResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static youtu.Imageclass.ClassResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static youtu.Imageclass.ClassResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static youtu.Imageclass.ClassResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static youtu.Imageclass.ClassResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static youtu.Imageclass.ClassResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static youtu.Imageclass.ClassResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static youtu.Imageclass.ClassResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(youtu.Imageclass.ClassResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code youtu.ClassResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements youtu.Imageclass.ClassResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return youtu.Imageclass.internal_static_youtu_ClassResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return youtu.Imageclass.internal_static_youtu_ClassResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                youtu.Imageclass.ClassResponse.class, youtu.Imageclass.ClassResponse.Builder.class);
      }

      // Construct using youtu.Imageclass.ClassResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        sim_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return youtu.Imageclass.internal_static_youtu_ClassResponse_descriptor;
      }

      public youtu.Imageclass.ClassResponse getDefaultInstanceForType() {
        return youtu.Imageclass.ClassResponse.getDefaultInstance();
      }

      public youtu.Imageclass.ClassResponse build() {
        youtu.Imageclass.ClassResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public youtu.Imageclass.ClassResponse buildPartial() {
        youtu.Imageclass.ClassResponse result = new youtu.Imageclass.ClassResponse(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          tags_ = new com.google.protobuf.UnmodifiableLazyStringList(
              tags_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.tags_ = tags_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          sim_ = java.util.Collections.unmodifiableList(sim_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.sim_ = sim_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof youtu.Imageclass.ClassResponse) {
          return mergeFrom((youtu.Imageclass.ClassResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(youtu.Imageclass.ClassResponse other) {
        if (other == youtu.Imageclass.ClassResponse.getDefaultInstance()) return this;
        if (!other.tags_.isEmpty()) {
          if (tags_.isEmpty()) {
            tags_ = other.tags_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTagsIsMutable();
            tags_.addAll(other.tags_);
          }
          onChanged();
        }
        if (!other.sim_.isEmpty()) {
          if (sim_.isEmpty()) {
            sim_ = other.sim_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureSimIsMutable();
            sim_.addAll(other.sim_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        youtu.Imageclass.ClassResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (youtu.Imageclass.ClassResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated string tags = 1;
      private com.google.protobuf.LazyStringList tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTagsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          tags_ = new com.google.protobuf.LazyStringArrayList(tags_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string tags = 1;</code>
       */
      public java.util.List<java.lang.String>
          getTagsList() {
        return java.util.Collections.unmodifiableList(tags_);
      }
      /**
       * <code>repeated string tags = 1;</code>
       */
      public int getTagsCount() {
        return tags_.size();
      }
      /**
       * <code>repeated string tags = 1;</code>
       */
      public java.lang.String getTags(int index) {
        return tags_.get(index);
      }
      /**
       * <code>repeated string tags = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTagsBytes(int index) {
        return tags_.getByteString(index);
      }
      /**
       * <code>repeated string tags = 1;</code>
       */
      public Builder setTags(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTagsIsMutable();
        tags_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tags = 1;</code>
       */
      public Builder addTags(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTagsIsMutable();
        tags_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tags = 1;</code>
       */
      public Builder addAllTags(
          java.lang.Iterable<java.lang.String> values) {
        ensureTagsIsMutable();
        super.addAll(values, tags_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tags = 1;</code>
       */
      public Builder clearTags() {
        tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tags = 1;</code>
       */
      public Builder addTagsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTagsIsMutable();
        tags_.add(value);
        onChanged();
        return this;
      }

      // repeated float sim = 2;
      private java.util.List<java.lang.Float> sim_ = java.util.Collections.emptyList();
      private void ensureSimIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          sim_ = new java.util.ArrayList<java.lang.Float>(sim_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated float sim = 2;</code>
       */
      public java.util.List<java.lang.Float>
          getSimList() {
        return java.util.Collections.unmodifiableList(sim_);
      }
      /**
       * <code>repeated float sim = 2;</code>
       */
      public int getSimCount() {
        return sim_.size();
      }
      /**
       * <code>repeated float sim = 2;</code>
       */
      public float getSim(int index) {
        return sim_.get(index);
      }
      /**
       * <code>repeated float sim = 2;</code>
       */
      public Builder setSim(
          int index, float value) {
        ensureSimIsMutable();
        sim_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float sim = 2;</code>
       */
      public Builder addSim(float value) {
        ensureSimIsMutable();
        sim_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float sim = 2;</code>
       */
      public Builder addAllSim(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureSimIsMutable();
        super.addAll(values, sim_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float sim = 2;</code>
       */
      public Builder clearSim() {
        sim_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:youtu.ClassResponse)
    }

    static {
      defaultInstance = new ClassResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:youtu.ClassResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_youtu_ClassRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_youtu_ClassRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_youtu_ClassResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_youtu_ClassResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020imageclass.proto\022\005youtu\"-\n\014ClassReques" +
      "t\022\017\n\007photoid\030\001 \002(\014\022\014\n\004data\030\002 \002(\014\"*\n\rClas" +
      "sResponse\022\014\n\004tags\030\001 \003(\t\022\013\n\003sim\030\002 \003(\002B\003\200\001" +
      "\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_youtu_ClassRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_youtu_ClassRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_youtu_ClassRequest_descriptor,
              new java.lang.String[] { "Photoid", "Data", });
          internal_static_youtu_ClassResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_youtu_ClassResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_youtu_ClassResponse_descriptor,
              new java.lang.String[] { "Tags", "Sim", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
