// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inspect.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "inspect.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace mtrpc {
namespace inspect {

namespace {

const ::google::protobuf::Descriptor* Request_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Request_reflection_ = NULL;
const ::google::protobuf::Descriptor* Response_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Response_reflection_ = NULL;
const ::google::protobuf::ServiceDescriptor* Machine_descriptor_ = NULL;
const ::google::protobuf::ServiceDescriptor* Process_descriptor_ = NULL;
const ::google::protobuf::ServiceDescriptor* Service_descriptor_ = NULL;
const ::google::protobuf::ServiceDescriptor* Application_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_inspect_2eproto() {
  protobuf_AddDesc_inspect_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "inspect.proto");
  GOOGLE_CHECK(file != NULL);
  Request_descriptor_ = file->message_type(0);
  static const int Request_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Request, json_),
  };
  Request_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Request_descriptor_,
      Request::default_instance_,
      Request_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Request, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Request, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Request));
  Response_descriptor_ = file->message_type(1);
  static const int Response_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Response, json_),
  };
  Response_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Response_descriptor_,
      Response::default_instance_,
      Response_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Response, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Response, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Response));
  Machine_descriptor_ = file->service(0);
  Process_descriptor_ = file->service(1);
  Service_descriptor_ = file->service(2);
  Application_descriptor_ = file->service(3);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_inspect_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Request_descriptor_, &Request::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Response_descriptor_, &Response::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_inspect_2eproto() {
  delete Request::default_instance_;
  delete Request_reflection_;
  delete Response::default_instance_;
  delete Response_reflection_;
}

void protobuf_AddDesc_inspect_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\rinspect.proto\022\rmtrpc.inspect\"\027\n\007Reques"
    "t\022\014\n\004json\030\001 \001(\014\"\030\n\010Response\022\014\n\004json\030\001 \001("
    "\0142\352\001\n\007Machine\0226\n\003cpu\022\026.mtrpc.inspect.Req"
    "uest\032\027.mtrpc.inspect.Response\0226\n\003mem\022\026.m"
    "trpc.inspect.Request\032\027.mtrpc.inspect.Res"
    "ponse\0226\n\003net\022\026.mtrpc.inspect.Request\032\027.m"
    "trpc.inspect.Response\0227\n\004disk\022\026.mtrpc.in"
    "spect.Request\032\027.mtrpc.inspect.Response2\241"
    "\002\n\007Process\0226\n\003cpu\022\026.mtrpc.inspect.Reques"
    "t\032\027.mtrpc.inspect.Response\0226\n\003mem\022\026.mtrp"
    "c.inspect.Request\032\027.mtrpc.inspect.Respon"
    "se\0226\n\003net\022\026.mtrpc.inspect.Request\032\027.mtrp"
    "c.inspect.Response\0227\n\004disk\022\026.mtrpc.inspe"
    "ct.Request\032\027.mtrpc.inspect.Response\0225\n\002f"
    "d\022\026.mtrpc.inspect.Request\032\027.mtrpc.inspec"
    "t.Response2\370\001\n\007Service\022:\n\007version\022\026.mtrp"
    "c.inspect.Request\032\027.mtrpc.inspect.Respon"
    "se\0226\n\003api\022\026.mtrpc.inspect.Request\032\027.mtrp"
    "c.inspect.Response\0229\n\006accept\022\026.mtrpc.ins"
    "pect.Request\032\027.mtrpc.inspect.Response\022>\n"
    "\013connections\022\026.mtrpc.inspect.Request\032\027.m"
    "trpc.inspect.Response2\215\001\n\013Application\022<\n"
    "\tinterface\022\026.mtrpc.inspect.Request\032\027.mtr"
    "pc.inspect.Response\022@\n\rrequeststatus\022\026.m"
    "trpc.inspect.Request\032\027.mtrpc.inspect.Res"
    "ponseB\003\200\001\001", 1010);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "inspect.proto", &protobuf_RegisterTypes);
  Request::default_instance_ = new Request();
  Response::default_instance_ = new Response();
  Request::default_instance_->InitAsDefaultInstance();
  Response::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_inspect_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_inspect_2eproto {
  StaticDescriptorInitializer_inspect_2eproto() {
    protobuf_AddDesc_inspect_2eproto();
  }
} static_descriptor_initializer_inspect_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Request::kJsonFieldNumber;
#endif  // !_MSC_VER

Request::Request()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Request::InitAsDefaultInstance() {
}

Request::Request(const Request& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Request::SharedCtor() {
  _cached_size_ = 0;
  json_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Request::~Request() {
  SharedDtor();
}

void Request::SharedDtor() {
  if (json_ != &::google::protobuf::internal::kEmptyString) {
    delete json_;
  }
  if (this != default_instance_) {
  }
}

void Request::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Request::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Request_descriptor_;
}

const Request& Request::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_inspect_2eproto();
  return *default_instance_;
}

Request* Request::default_instance_ = NULL;

Request* Request::New() const {
  return new Request;
}

void Request::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_json()) {
      if (json_ != &::google::protobuf::internal::kEmptyString) {
        json_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Request::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bytes json = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_json()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Request::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional bytes json = 1;
  if (has_json()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      1, this->json(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Request::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional bytes json = 1;
  if (has_json()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->json(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Request::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional bytes json = 1;
    if (has_json()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->json());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Request::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Request* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Request*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Request::MergeFrom(const Request& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_json()) {
      set_json(from.json());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Request::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Request::CopyFrom(const Request& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Request::IsInitialized() const {

  return true;
}

void Request::Swap(Request* other) {
  if (other != this) {
    std::swap(json_, other->json_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Request::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Request_descriptor_;
  metadata.reflection = Request_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int Response::kJsonFieldNumber;
#endif  // !_MSC_VER

Response::Response()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Response::InitAsDefaultInstance() {
}

Response::Response(const Response& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Response::SharedCtor() {
  _cached_size_ = 0;
  json_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Response::~Response() {
  SharedDtor();
}

void Response::SharedDtor() {
  if (json_ != &::google::protobuf::internal::kEmptyString) {
    delete json_;
  }
  if (this != default_instance_) {
  }
}

void Response::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Response::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Response_descriptor_;
}

const Response& Response::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_inspect_2eproto();
  return *default_instance_;
}

Response* Response::default_instance_ = NULL;

Response* Response::New() const {
  return new Response;
}

void Response::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_json()) {
      if (json_ != &::google::protobuf::internal::kEmptyString) {
        json_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Response::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bytes json = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_json()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Response::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional bytes json = 1;
  if (has_json()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      1, this->json(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Response::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional bytes json = 1;
  if (has_json()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->json(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Response::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional bytes json = 1;
    if (has_json()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->json());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Response::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Response* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Response*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Response::MergeFrom(const Response& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_json()) {
      set_json(from.json());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Response::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Response::CopyFrom(const Response& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Response::IsInitialized() const {

  return true;
}

void Response::Swap(Response* other) {
  if (other != this) {
    std::swap(json_, other->json_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Response::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Response_descriptor_;
  metadata.reflection = Response_reflection_;
  return metadata;
}


// ===================================================================

Machine::~Machine() {}

const ::google::protobuf::ServiceDescriptor* Machine::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Machine_descriptor_;
}

const ::google::protobuf::ServiceDescriptor* Machine::GetDescriptor() {
  protobuf_AssignDescriptorsOnce();
  return Machine_descriptor_;
}

void Machine::cpu(::google::protobuf::RpcController* controller,
                         const ::mtrpc::inspect::Request*,
                         ::mtrpc::inspect::Response*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method cpu() not implemented.");
  done->Run();
}

void Machine::mem(::google::protobuf::RpcController* controller,
                         const ::mtrpc::inspect::Request*,
                         ::mtrpc::inspect::Response*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method mem() not implemented.");
  done->Run();
}

void Machine::net(::google::protobuf::RpcController* controller,
                         const ::mtrpc::inspect::Request*,
                         ::mtrpc::inspect::Response*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method net() not implemented.");
  done->Run();
}

void Machine::disk(::google::protobuf::RpcController* controller,
                         const ::mtrpc::inspect::Request*,
                         ::mtrpc::inspect::Response*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method disk() not implemented.");
  done->Run();
}

void Machine::CallMethod(const ::google::protobuf::MethodDescriptor* method,
                             ::google::protobuf::RpcController* controller,
                             const ::google::protobuf::Message* request,
                             ::google::protobuf::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), Machine_descriptor_);
  switch(method->index()) {
    case 0:
      cpu(controller,
             ::google::protobuf::down_cast<const ::mtrpc::inspect::Request*>(request),
             ::google::protobuf::down_cast< ::mtrpc::inspect::Response*>(response),
             done);
      break;
    case 1:
      mem(controller,
             ::google::protobuf::down_cast<const ::mtrpc::inspect::Request*>(request),
             ::google::protobuf::down_cast< ::mtrpc::inspect::Response*>(response),
             done);
      break;
    case 2:
      net(controller,
             ::google::protobuf::down_cast<const ::mtrpc::inspect::Request*>(request),
             ::google::protobuf::down_cast< ::mtrpc::inspect::Response*>(response),
             done);
      break;
    case 3:
      disk(controller,
             ::google::protobuf::down_cast<const ::mtrpc::inspect::Request*>(request),
             ::google::protobuf::down_cast< ::mtrpc::inspect::Response*>(response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::google::protobuf::Message& Machine::GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::mtrpc::inspect::Request::default_instance();
    case 1:
      return ::mtrpc::inspect::Request::default_instance();
    case 2:
      return ::mtrpc::inspect::Request::default_instance();
    case 3:
      return ::mtrpc::inspect::Request::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *reinterpret_cast< ::google::protobuf::Message*>(NULL);
  }
}

const ::google::protobuf::Message& Machine::GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::mtrpc::inspect::Response::default_instance();
    case 1:
      return ::mtrpc::inspect::Response::default_instance();
    case 2:
      return ::mtrpc::inspect::Response::default_instance();
    case 3:
      return ::mtrpc::inspect::Response::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *reinterpret_cast< ::google::protobuf::Message*>(NULL);
  }
}

Machine_Stub::Machine_Stub(::google::protobuf::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
Machine_Stub::Machine_Stub(
    ::google::protobuf::RpcChannel* channel,
    ::google::protobuf::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::google::protobuf::Service::STUB_OWNS_CHANNEL) {}
Machine_Stub::~Machine_Stub() {
  if (owns_channel_) delete channel_;
}

void Machine_Stub::cpu(::google::protobuf::RpcController* controller,
                              const ::mtrpc::inspect::Request* request,
                              ::mtrpc::inspect::Response* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}
void Machine_Stub::mem(::google::protobuf::RpcController* controller,
                              const ::mtrpc::inspect::Request* request,
                              ::mtrpc::inspect::Response* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(1),
                       controller, request, response, done);
}
void Machine_Stub::net(::google::protobuf::RpcController* controller,
                              const ::mtrpc::inspect::Request* request,
                              ::mtrpc::inspect::Response* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(2),
                       controller, request, response, done);
}
void Machine_Stub::disk(::google::protobuf::RpcController* controller,
                              const ::mtrpc::inspect::Request* request,
                              ::mtrpc::inspect::Response* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(3),
                       controller, request, response, done);
}
// ===================================================================

Process::~Process() {}

const ::google::protobuf::ServiceDescriptor* Process::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Process_descriptor_;
}

const ::google::protobuf::ServiceDescriptor* Process::GetDescriptor() {
  protobuf_AssignDescriptorsOnce();
  return Process_descriptor_;
}

void Process::cpu(::google::protobuf::RpcController* controller,
                         const ::mtrpc::inspect::Request*,
                         ::mtrpc::inspect::Response*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method cpu() not implemented.");
  done->Run();
}

void Process::mem(::google::protobuf::RpcController* controller,
                         const ::mtrpc::inspect::Request*,
                         ::mtrpc::inspect::Response*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method mem() not implemented.");
  done->Run();
}

void Process::net(::google::protobuf::RpcController* controller,
                         const ::mtrpc::inspect::Request*,
                         ::mtrpc::inspect::Response*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method net() not implemented.");
  done->Run();
}

void Process::disk(::google::protobuf::RpcController* controller,
                         const ::mtrpc::inspect::Request*,
                         ::mtrpc::inspect::Response*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method disk() not implemented.");
  done->Run();
}

void Process::fd(::google::protobuf::RpcController* controller,
                         const ::mtrpc::inspect::Request*,
                         ::mtrpc::inspect::Response*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method fd() not implemented.");
  done->Run();
}

void Process::CallMethod(const ::google::protobuf::MethodDescriptor* method,
                             ::google::protobuf::RpcController* controller,
                             const ::google::protobuf::Message* request,
                             ::google::protobuf::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), Process_descriptor_);
  switch(method->index()) {
    case 0:
      cpu(controller,
             ::google::protobuf::down_cast<const ::mtrpc::inspect::Request*>(request),
             ::google::protobuf::down_cast< ::mtrpc::inspect::Response*>(response),
             done);
      break;
    case 1:
      mem(controller,
             ::google::protobuf::down_cast<const ::mtrpc::inspect::Request*>(request),
             ::google::protobuf::down_cast< ::mtrpc::inspect::Response*>(response),
             done);
      break;
    case 2:
      net(controller,
             ::google::protobuf::down_cast<const ::mtrpc::inspect::Request*>(request),
             ::google::protobuf::down_cast< ::mtrpc::inspect::Response*>(response),
             done);
      break;
    case 3:
      disk(controller,
             ::google::protobuf::down_cast<const ::mtrpc::inspect::Request*>(request),
             ::google::protobuf::down_cast< ::mtrpc::inspect::Response*>(response),
             done);
      break;
    case 4:
      fd(controller,
             ::google::protobuf::down_cast<const ::mtrpc::inspect::Request*>(request),
             ::google::protobuf::down_cast< ::mtrpc::inspect::Response*>(response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::google::protobuf::Message& Process::GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::mtrpc::inspect::Request::default_instance();
    case 1:
      return ::mtrpc::inspect::Request::default_instance();
    case 2:
      return ::mtrpc::inspect::Request::default_instance();
    case 3:
      return ::mtrpc::inspect::Request::default_instance();
    case 4:
      return ::mtrpc::inspect::Request::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *reinterpret_cast< ::google::protobuf::Message*>(NULL);
  }
}

const ::google::protobuf::Message& Process::GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::mtrpc::inspect::Response::default_instance();
    case 1:
      return ::mtrpc::inspect::Response::default_instance();
    case 2:
      return ::mtrpc::inspect::Response::default_instance();
    case 3:
      return ::mtrpc::inspect::Response::default_instance();
    case 4:
      return ::mtrpc::inspect::Response::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *reinterpret_cast< ::google::protobuf::Message*>(NULL);
  }
}

Process_Stub::Process_Stub(::google::protobuf::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
Process_Stub::Process_Stub(
    ::google::protobuf::RpcChannel* channel,
    ::google::protobuf::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::google::protobuf::Service::STUB_OWNS_CHANNEL) {}
Process_Stub::~Process_Stub() {
  if (owns_channel_) delete channel_;
}

void Process_Stub::cpu(::google::protobuf::RpcController* controller,
                              const ::mtrpc::inspect::Request* request,
                              ::mtrpc::inspect::Response* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}
void Process_Stub::mem(::google::protobuf::RpcController* controller,
                              const ::mtrpc::inspect::Request* request,
                              ::mtrpc::inspect::Response* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(1),
                       controller, request, response, done);
}
void Process_Stub::net(::google::protobuf::RpcController* controller,
                              const ::mtrpc::inspect::Request* request,
                              ::mtrpc::inspect::Response* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(2),
                       controller, request, response, done);
}
void Process_Stub::disk(::google::protobuf::RpcController* controller,
                              const ::mtrpc::inspect::Request* request,
                              ::mtrpc::inspect::Response* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(3),
                       controller, request, response, done);
}
void Process_Stub::fd(::google::protobuf::RpcController* controller,
                              const ::mtrpc::inspect::Request* request,
                              ::mtrpc::inspect::Response* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(4),
                       controller, request, response, done);
}
// ===================================================================

Service::~Service() {}

const ::google::protobuf::ServiceDescriptor* Service::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Service_descriptor_;
}

const ::google::protobuf::ServiceDescriptor* Service::GetDescriptor() {
  protobuf_AssignDescriptorsOnce();
  return Service_descriptor_;
}

void Service::version(::google::protobuf::RpcController* controller,
                         const ::mtrpc::inspect::Request*,
                         ::mtrpc::inspect::Response*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method version() not implemented.");
  done->Run();
}

void Service::api(::google::protobuf::RpcController* controller,
                         const ::mtrpc::inspect::Request*,
                         ::mtrpc::inspect::Response*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method api() not implemented.");
  done->Run();
}

void Service::accept(::google::protobuf::RpcController* controller,
                         const ::mtrpc::inspect::Request*,
                         ::mtrpc::inspect::Response*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method accept() not implemented.");
  done->Run();
}

void Service::connections(::google::protobuf::RpcController* controller,
                         const ::mtrpc::inspect::Request*,
                         ::mtrpc::inspect::Response*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method connections() not implemented.");
  done->Run();
}

void Service::CallMethod(const ::google::protobuf::MethodDescriptor* method,
                             ::google::protobuf::RpcController* controller,
                             const ::google::protobuf::Message* request,
                             ::google::protobuf::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), Service_descriptor_);
  switch(method->index()) {
    case 0:
      version(controller,
             ::google::protobuf::down_cast<const ::mtrpc::inspect::Request*>(request),
             ::google::protobuf::down_cast< ::mtrpc::inspect::Response*>(response),
             done);
      break;
    case 1:
      api(controller,
             ::google::protobuf::down_cast<const ::mtrpc::inspect::Request*>(request),
             ::google::protobuf::down_cast< ::mtrpc::inspect::Response*>(response),
             done);
      break;
    case 2:
      accept(controller,
             ::google::protobuf::down_cast<const ::mtrpc::inspect::Request*>(request),
             ::google::protobuf::down_cast< ::mtrpc::inspect::Response*>(response),
             done);
      break;
    case 3:
      connections(controller,
             ::google::protobuf::down_cast<const ::mtrpc::inspect::Request*>(request),
             ::google::protobuf::down_cast< ::mtrpc::inspect::Response*>(response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::google::protobuf::Message& Service::GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::mtrpc::inspect::Request::default_instance();
    case 1:
      return ::mtrpc::inspect::Request::default_instance();
    case 2:
      return ::mtrpc::inspect::Request::default_instance();
    case 3:
      return ::mtrpc::inspect::Request::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *reinterpret_cast< ::google::protobuf::Message*>(NULL);
  }
}

const ::google::protobuf::Message& Service::GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::mtrpc::inspect::Response::default_instance();
    case 1:
      return ::mtrpc::inspect::Response::default_instance();
    case 2:
      return ::mtrpc::inspect::Response::default_instance();
    case 3:
      return ::mtrpc::inspect::Response::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *reinterpret_cast< ::google::protobuf::Message*>(NULL);
  }
}

Service_Stub::Service_Stub(::google::protobuf::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
Service_Stub::Service_Stub(
    ::google::protobuf::RpcChannel* channel,
    ::google::protobuf::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::google::protobuf::Service::STUB_OWNS_CHANNEL) {}
Service_Stub::~Service_Stub() {
  if (owns_channel_) delete channel_;
}

void Service_Stub::version(::google::protobuf::RpcController* controller,
                              const ::mtrpc::inspect::Request* request,
                              ::mtrpc::inspect::Response* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}
void Service_Stub::api(::google::protobuf::RpcController* controller,
                              const ::mtrpc::inspect::Request* request,
                              ::mtrpc::inspect::Response* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(1),
                       controller, request, response, done);
}
void Service_Stub::accept(::google::protobuf::RpcController* controller,
                              const ::mtrpc::inspect::Request* request,
                              ::mtrpc::inspect::Response* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(2),
                       controller, request, response, done);
}
void Service_Stub::connections(::google::protobuf::RpcController* controller,
                              const ::mtrpc::inspect::Request* request,
                              ::mtrpc::inspect::Response* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(3),
                       controller, request, response, done);
}
// ===================================================================

Application::~Application() {}

const ::google::protobuf::ServiceDescriptor* Application::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Application_descriptor_;
}

const ::google::protobuf::ServiceDescriptor* Application::GetDescriptor() {
  protobuf_AssignDescriptorsOnce();
  return Application_descriptor_;
}

void Application::interface(::google::protobuf::RpcController* controller,
                         const ::mtrpc::inspect::Request*,
                         ::mtrpc::inspect::Response*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method interface() not implemented.");
  done->Run();
}

void Application::requeststatus(::google::protobuf::RpcController* controller,
                         const ::mtrpc::inspect::Request*,
                         ::mtrpc::inspect::Response*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method requeststatus() not implemented.");
  done->Run();
}

void Application::CallMethod(const ::google::protobuf::MethodDescriptor* method,
                             ::google::protobuf::RpcController* controller,
                             const ::google::protobuf::Message* request,
                             ::google::protobuf::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), Application_descriptor_);
  switch(method->index()) {
    case 0:
      interface(controller,
             ::google::protobuf::down_cast<const ::mtrpc::inspect::Request*>(request),
             ::google::protobuf::down_cast< ::mtrpc::inspect::Response*>(response),
             done);
      break;
    case 1:
      requeststatus(controller,
             ::google::protobuf::down_cast<const ::mtrpc::inspect::Request*>(request),
             ::google::protobuf::down_cast< ::mtrpc::inspect::Response*>(response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::google::protobuf::Message& Application::GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::mtrpc::inspect::Request::default_instance();
    case 1:
      return ::mtrpc::inspect::Request::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *reinterpret_cast< ::google::protobuf::Message*>(NULL);
  }
}

const ::google::protobuf::Message& Application::GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::mtrpc::inspect::Response::default_instance();
    case 1:
      return ::mtrpc::inspect::Response::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *reinterpret_cast< ::google::protobuf::Message*>(NULL);
  }
}

Application_Stub::Application_Stub(::google::protobuf::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
Application_Stub::Application_Stub(
    ::google::protobuf::RpcChannel* channel,
    ::google::protobuf::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::google::protobuf::Service::STUB_OWNS_CHANNEL) {}
Application_Stub::~Application_Stub() {
  if (owns_channel_) delete channel_;
}

void Application_Stub::interface(::google::protobuf::RpcController* controller,
                              const ::mtrpc::inspect::Request* request,
                              ::mtrpc::inspect::Response* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}
void Application_Stub::requeststatus(::google::protobuf::RpcController* controller,
                              const ::mtrpc::inspect::Request* request,
                              ::mtrpc::inspect::Response* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(1),
                       controller, request, response, done);
}

// @@protoc_insertion_point(namespace_scope)

}  // namespace inspect
}  // namespace mtrpc

// @@protoc_insertion_point(global_scope)
